### PR TITLE
escape parens in tag values

### LINKED ISSUE #74: Toggling a task as done twice duplicates parentheses from header
This happens when cancelling as well.
insta

### PR DESCRIPTION
**Pull request by paulroub**
per [Proposal, require that both ( and ) are always escaped in tag values?](http://support.hogbaysoftware.com/t/proposal-require-that-both-and-are-always-escaped-in-tag-values/1820) (Hog Bay TaskPaper support), to fix #74 

Escape parens when adding a tag with a value (among others, collected project names when marking an item done). Look for an *unescaped* right paren when retrieving a tag's value.

### CODE REVIEW

**Comment by irrationalistic** [comment]
Thanks for coming up with a solution for this! I'm hoping there's a way we can modify this to not introduce any extra syntax into the content though. Maybe the right way is to not use regular expressions and instead just manually check character-to-character in `getAllTags`. That way we don't have to mess with write, just read and parse! Thoughts?

**Comment by paulroub** [comment]
Without the extra syntax, how would you know when you've reached the end of the tag, and not just an embedded `)`?

**Comment by irrationalistic** [comment]
You'd end up using counters for open/close. Like every `(` is +1 and every `)` is -1, then you read characters until the value becomes 0 (which means you've closed out the starting `(`) or you reach the end of the current line!

**Comment by paulroub** [comment]
Nope. No guarantee that someone won't name a project `# I am bad at parens)`, and then your count will be wrong. Hence the need for escaping in this one (slightly weird) case.

**Comment by paulroub** [comment]
Nope. No guarantee that someone won't name a project `# I am bad at parens)`, and then your count will be wrong. Hence the need for escaping in this one (slightly weird) case.

**Comment by irrationalistic** [comment]
Makes sense. Based on your code, this would only apply to tags added via the package, so I think this is fine :)

You'll just have to rebase on the fixed tests!

**Comment by irrationalistic** [comment]
Looks good to me! I'll merge it now and then put out a release later today :) Thanks for your input and help on this!

**Pull request merged**
