### PR TITLE
status bar count fix

### PR DESCRIPTION
**Pull request by paulroub**
Make done/cancelled token names consistent, fixing #82

### CODE REVIEW

**Comment by irrationalistic** [comment]
Thanks for doing this! Could you double check that the syntax highlighting still works when you have markdown within the task item? That was one of the reasons I kept changing these around :)

**Comment by paulroub** [comment]
As far as I can tell, the highlighting is unchanged when I revert to the release.

**Comment by irrationalistic** [comment]
I pulled this in locally and it does check out, but i think we actually should re-visit the code. Changing the classnames like this is a bit of a bandaid (primarily because i didn't really understand how to pull in the markdown syntax!) I have a fix locally that properly enables markdown which i'll put up as a separate pull request for you to take a look :)

**Comment by irrationalistic** [comment]
Closing this in favor of #85

**Pull request closed without merging**
