### PR TITLE
Add clock in feature

### PR DESCRIPTION
**Pull request by JohannWeging**
This commit set adds the capability to clock in to tasks.
You can clock in and clock out, the time will be summed up.
Automatically clock out when running done or cancel.

Running the clock command on a task:
```
☐ foobar
☐ foobar @clock(2015-02-12 22:53)  // run clock (clock in)
☐ foobar @time(0.0:2) // run clock after 2 min time stamp d.hh.mm (clock out)
☐ foobar @time(0.0:2) @clock(2015-02-12 22:57) // run clock (clock in again)
✔ foobar @time(0.0:4) @done(2015-02-12 22:59) // run done after 2 min, time gets added 
```

Have a look at the OS X key binding, you may have a better idea. I don't know if ctrl-t will work, it's alt-t atm.
And have a look at the tasks.less `@clock` should be red (error) and `@time` subtle.

I didn't modify the patterns in the tasks.cson in the lib dir, do i need to add something there?

Maybe it comes in handy,
have a nice day.

### CODE REVIEW

**Comment by irrationalistic** [comment]
@JohannWeging Thanks so much for posting this! This is a really neat feature.

I've been thinking about it a bit, trying to find a good way to integrate it. The internal debate is between core integration and making it a secondary plugin (like autocomplete and autocomplete-snippets). Do you have any thoughts on that?

**Comment by JohannWeging** [comment]
I would integrate it into the core. A secondary plugin would make sense if you want to add bigger features. Registering a new new engine for completion is a whole different level than handling tasks. A secondary plugin could be something like drawing fancy graphs about how long you work on a project etc.. As long as it's only handling tasks, put it in the core.

**Comment by irrationalistic** [comment]
The parser, at least right now, handles tags by giving them classes of whatever the attribute is. For instance, a tag of `@clock(...)` would receive the class `.clock` plus any contextual classes like `.done` or `.cancelled`. Is that what you mean by those basic functions?

**Comment by JohannWeging** [comment]
The following is only a thought experiment and a rough draft.

I mean a parser for the todo files written in coffescript.
You have the todo file:
```
☐ foo @important(very)

MyProject [2/3] (time spent on project):
☐ foo @done(timestamp) @time(spent on task)
☐ bar
☐ baz @done(timestamp) @time(spent on task)
```
The project has some stuff added like task counter and a overall time measurement.
With the current implementation these feature are not easy to add.

A parser will provide a object structure for example:
```json
[
    {
        "type": "task",
        "text": "foobar",
        "tags": [{"name": "important", "text": "very"}]
    },
    {
        "type": "project",
       "name": "MyProject",
       "tasks":
       [
          //all the tasks here like above
       ]
    }
]
```
This would make it easier to interact with the todo file.

At the moment if you want to add a tag:
```coffeescript
line += " @project(#{lastProject.trim()})" if lastProject
```
But if you have a task object you could do some thing like:
```coffescript
task.addTag "project", lastProject.trim() if lastProject
```
This function sets the tag or update it if it's already there.

**Comment by irrationalistic** [comment]
Ah, I see what you are saying. I'll give it some thought! Thanks for the great ideas!

**Comment by JohannWeging** [comment]
I rebased my changes on top of your 1.3.0 changes.

**Comment by irrationalistic** [comment]
Based on your feedback and the need for a better core codebase, I've been researching and working on the new version 2! It's improved in many ways, but there is a system of utilities for improving interaction with todo files. While not a parser, mainly due to performance reasons, it does have methods for easily adding and manipulating tags for tasks as well as discovering more information about the rest of the file in different ways.

I've also kept your thoughts on the clocking feature in mind and I've decided that I don't really want it to be a part of the core, but I want it to lead the improvements for adding 3rd party plugins. Something that can integrate with the core functionality and allow features like this one to be injected in, or at least sit beside, the base. I'll be working on that functionality next, so if you are still interested, this might be a better place to introduce your features.

**Comment by irrationalistic** [comment]
I'm going to close this pull request for now!

**Pull request closed without merging**
